#[derive(Debug, PartialEq, Copy, Clone)]
pub enum Token<'a> {
    Ident(&'a str),
    Star,
    ForwardSlash,
    BackwardSlash,
    SingleQuote,
    DoubleQuote,
    Colon,
    Comma,
    SemiColon,
    Space,
    Newline,
    Tab,
    Return,
    OpenBrace,
    ClosingBrace,
    OpenCurlyBrace,
    ClosingCurlyBrace,
    Eof,
}
