#[derive(Debug, PartialEq, Copy, Clone)]
pub enum Token<'a> {
    Operator(&'a str),
    Id(&'a str),
    Class(&'a str),
    Tag(&'a str),
    Rule(&'a str),
    Value(&'a str),
    Comment(&'a str),
    Colon,
    Comma,
    SemiColon,
    Space,
    Newline,
    Tab,
    Return,
    OpenBrace,
    ClosingBrace,
    OpenCurlyBrace,
    ClosingCurlyBrace,
    Eof,
    Unknown(&'a str),
}
